// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squadra;
using Squadra.Server.Context;

#nullable disable

namespace Squadra.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250912173012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Squadra.Jezyk", b =>
                {
                    b.Property<int>("JezykId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JezykId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JezykId");

                    b.ToTable("Jezyk", (string)null);
                });

            modelBuilder.Entity("Squadra.JezykProfilu", b =>
                {
                    b.Property<int>("JezykId")
                        .HasColumnType("int")
                        .HasColumnName("id_jezyka");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownika");

                    b.Property<int>("StopienBieglosciId")
                        .HasColumnType("int")
                        .HasColumnName("id_stopnia_bieglosci");

                    b.HasKey("JezykId", "UzytkownikId")
                        .HasName("id_jezyk_uzytkownika");

                    b.HasIndex("StopienBieglosciId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("JezykProfilu", (string)null);
                });

            modelBuilder.Entity("Squadra.Kraj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Kraj", (string)null);
                });

            modelBuilder.Entity("Squadra.Profil", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<byte[]>("Awatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pseudonim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("id_regionu");

                    b.Property<string>("Zaimki")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdUzytkownika");

                    b.HasIndex("RegionId");

                    b.ToTable("Profil", (string)null);
                });

            modelBuilder.Entity("Squadra.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KrajId")
                        .HasColumnType("int")
                        .HasColumnName("id_kraju");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KrajId");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Squadra.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Online"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Away"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Do not disturb"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Invisible"
                        });
                });

            modelBuilder.Entity("Squadra.StopienBieglosciJezyka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wartosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StopienBieglosciJezyka", (string)null);
                });

            modelBuilder.Entity("Squadra.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumerTelefonu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_statusu");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Uzytkownik", (string)null);
                });

            modelBuilder.Entity("Squadra.JezykProfilu", b =>
                {
                    b.HasOne("Squadra.Jezyk", "Jezyk")
                        .WithMany("JezykProfiluCollection")
                        .HasForeignKey("JezykId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykProfilu_Jezyk");

                    b.HasOne("Squadra.StopienBieglosciJezyka", "StopienBieglosciJezyka")
                        .WithMany("JezykUzytkownikaCollection")
                        .HasForeignKey("StopienBieglosciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykUzytkownika_StopienBieglosci");

                    b.HasOne("Squadra.Profil", "Profil")
                        .WithMany("JezykUzytkownikaCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykProfilu_Profil");

                    b.Navigation("Jezyk");

                    b.Navigation("Profil");

                    b.Navigation("StopienBieglosciJezyka");
                });

            modelBuilder.Entity("Squadra.Profil", b =>
                {
                    b.HasOne("Squadra.Region", "Region")
                        .WithMany("ProfilCollection")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Profil_Region");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Squadra.Region", b =>
                {
                    b.HasOne("Squadra.Kraj", "Kraj")
                        .WithMany("RegionCollection")
                        .HasForeignKey("KrajId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Region_Kraj");

                    b.Navigation("Kraj");
                });

            modelBuilder.Entity("Squadra.Uzytkownik", b =>
                {
                    b.HasOne("Squadra.Profil", "Profil")
                        .WithOne("Uzytkownik")
                        .HasForeignKey("Squadra.Uzytkownik", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Uzytkownik_Profil");

                    b.HasOne("Squadra.Status", "Status")
                        .WithMany("UzytkownikCollection")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Uzytkownik_Status");

                    b.Navigation("Profil");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Squadra.Jezyk", b =>
                {
                    b.Navigation("JezykProfiluCollection");
                });

            modelBuilder.Entity("Squadra.Kraj", b =>
                {
                    b.Navigation("RegionCollection");
                });

            modelBuilder.Entity("Squadra.Profil", b =>
                {
                    b.Navigation("JezykUzytkownikaCollection");

                    b.Navigation("Uzytkownik")
                        .IsRequired();
                });

            modelBuilder.Entity("Squadra.Region", b =>
                {
                    b.Navigation("ProfilCollection");
                });

            modelBuilder.Entity("Squadra.Status", b =>
                {
                    b.Navigation("UzytkownikCollection");
                });

            modelBuilder.Entity("Squadra.StopienBieglosciJezyka", b =>
                {
                    b.Navigation("JezykUzytkownikaCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
