// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squadra.Server.Context;

#nullable disable

namespace Squadra.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408173825_Dodanie_kolumny_porownywalna_wartosc_liczbowa_do_statystyki_uzytkownika")]
    partial class Dodanie_kolumny_porownywalna_wartosc_liczbowa_do_statystyki_uzytkownika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownika", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("GraId")
                        .HasColumnType("int");

                    b.HasKey("UzytkownikId", "GraId")
                        .HasName("id_gra_uzytkownika");

                    b.HasIndex("GraId");

                    b.ToTable("GraUzytkownika", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownikaNaPlatformie", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("GraId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformaId")
                        .HasColumnType("int");

                    b.HasKey("UzytkownikId", "GraId", "PlatformaId")
                        .HasName("id_gra_uzytkownika_na_platformie");

                    b.HasIndex("PlatformaId");

                    b.ToTable("GraUzytkownikaNaPlatformie", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Platformy.Models.Platforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Platforma", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Platformy.Models.UzytkownikPlatforma", b =>
                {
                    b.Property<int>("PlatformaId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<string>("PseudonimNaPlatformie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PlatformaId", "UzytkownikId")
                        .HasName("id_uzytkownik_platforma");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("UzytkownikPlatforma", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Powiadomienia.Models.Powiadomienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWyslania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PowiazanyObiektId")
                        .HasColumnType("int");

                    b.Property<string>("PowiazanyObiektNazwa")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tresc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypPowiadomieniaId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypPowiadomieniaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Powiadomienie", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Powiadomienia.Models.TypPowiadomienia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypPowiadomienia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Systemowe"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Zaproszenie do znajomych"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Zaakceptowano zaproszenie do znajomych"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Odrzucono zaproszenie do znajomych"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Usunieto cie ze znajomych"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Jezyk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Jezyk", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "polski"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "angielski"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "niemiecki"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "francuski"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "hiszpański"
                        },
                        new
                        {
                            Id = 6,
                            Nazwa = "japoński"
                        },
                        new
                        {
                            Id = 7,
                            Nazwa = "rosyjski"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.JezykProfilu", b =>
                {
                    b.Property<int>("JezykId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("StopienBieglosciId")
                        .HasColumnType("int");

                    b.HasKey("JezykId", "UzytkownikId")
                        .HasName("id_jezyk_uzytkownika");

                    b.HasIndex("StopienBieglosciId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("JezykProfilu", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Kraj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Kraj", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Polska"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Anglia"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Profil", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<byte[]>("Awatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pseudonim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Zaimki")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUzytkownika");

                    b.HasIndex("RegionId");

                    b.HasIndex("StatusId");

                    b.ToTable("Profil", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KrajId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KrajId");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KrajId = 1,
                            Nazwa = "Nie określono"
                        },
                        new
                        {
                            Id = 2,
                            KrajId = 1,
                            Nazwa = "Mazowieckie"
                        },
                        new
                        {
                            Id = 3,
                            KrajId = 1,
                            Nazwa = "Dolnoslaskie"
                        },
                        new
                        {
                            Id = 4,
                            KrajId = 1,
                            Nazwa = "Lubelskie"
                        },
                        new
                        {
                            Id = 5,
                            KrajId = 1,
                            Nazwa = "Lubuskie"
                        },
                        new
                        {
                            Id = 6,
                            KrajId = 1,
                            Nazwa = "Podkarpackie"
                        },
                        new
                        {
                            Id = 7,
                            KrajId = 1,
                            Nazwa = "Podlaskie"
                        },
                        new
                        {
                            Id = 8,
                            KrajId = 1,
                            Nazwa = "Zachodniopomorskie"
                        },
                        new
                        {
                            Id = 9,
                            KrajId = 1,
                            Nazwa = "Wielkopolskie"
                        },
                        new
                        {
                            Id = 10,
                            KrajId = 2,
                            Nazwa = "Nie określono"
                        },
                        new
                        {
                            Id = 11,
                            KrajId = 2,
                            Nazwa = "West Midlands"
                        },
                        new
                        {
                            Id = 12,
                            KrajId = 2,
                            Nazwa = "South West England"
                        },
                        new
                        {
                            Id = 13,
                            KrajId = 2,
                            Nazwa = "South East England"
                        },
                        new
                        {
                            Id = 14,
                            KrajId = 2,
                            Nazwa = "North West England"
                        },
                        new
                        {
                            Id = 15,
                            KrajId = 2,
                            Nazwa = "North East England"
                        },
                        new
                        {
                            Id = 16,
                            KrajId = 2,
                            Nazwa = "Greater London"
                        },
                        new
                        {
                            Id = 17,
                            KrajId = 2,
                            Nazwa = "East od England"
                        },
                        new
                        {
                            Id = 18,
                            KrajId = 2,
                            Nazwa = "East Midlands"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Dostępny"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Zaraz wracam"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Nie przeszkadzać"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Niewidoczny"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Offline"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.StopienBieglosciJezyka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Wartosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StopienBieglosciJezyka", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Podstawowy",
                            Wartosc = 1
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Średnio-zaawansowany",
                            Wartosc = 2
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Zaawansowany",
                            Wartosc = 3
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("CzyToCzasRozgrywki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IdGry")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdGry");

                    b.ToTable("Kategoria", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdGry")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdGry");

                    b.ToTable("Rola", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Statystyka", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.HasIndex("RolaId");

                    b.ToTable("Statystyka", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.StatystykaUzytkownika", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("StatystykaId")
                        .HasColumnType("int");

                    b.Property<int?>("PorownywalnaWartoscLiczbowa")
                        .HasColumnType("int");

                    b.Property<string>("Wartosc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UzytkownikId", "StatystykaId")
                        .HasName("id_statystyka_uzytkownika");

                    b.HasIndex("StatystykaId");

                    b.ToTable("StatystykaUzytkownika", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdNaZewnetrznymSerwisie")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginNaZewnetrznymSerwisie")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("OstatniaAktywnosc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Wiadomosci.Models.TypWiadomosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypWiadomosci", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Prywatna"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Do gildii"
                        });
                });

            modelBuilder.Entity("Squadra.Server.Modules.Wiadomosci.Models.Wiadomosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWyslania")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdNadawcy")
                        .HasColumnType("int");

                    b.Property<int>("IdOdbiorcy")
                        .HasColumnType("int");

                    b.Property<int>("IdTypuWiadomosci")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IdNadawcy");

                    b.HasIndex("IdOdbiorcy");

                    b.HasIndex("IdTypuWiadomosci");

                    b.ToTable("Wiadomosc", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.WspieraneGry.Models.GraNaPlatformie", b =>
                {
                    b.Property<int>("IdWspieranejGry")
                        .HasColumnType("int");

                    b.Property<int>("IdPlatformy")
                        .HasColumnType("int");

                    b.HasKey("IdWspieranejGry", "IdPlatformy")
                        .HasName("id_gra_na_platformie");

                    b.HasIndex("IdPlatformy");

                    b.ToTable("GraNaPlatformie", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Wydawca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("WspieranaGra", (string)null);
                });

            modelBuilder.Entity("Squadra.Server.Modules.Znajomosci.Models.Znajomi", b =>
                {
                    b.Property<int>("IdUzytkownika1")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika2")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataNawiazaniaZnajomosci")
                        .HasColumnType("date");

                    b.Property<DateTime?>("OstatnieOtwarcieCzatuUzytkownika1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OstatnieOtwarcieCzatuUzytkownika2")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUzytkownika1", "IdUzytkownika2")
                        .HasName("id_znajomi");

                    b.HasIndex("IdUzytkownika2");

                    b.ToTable("Znajomi", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownika", b =>
                {
                    b.HasOne("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", "Gra")
                        .WithMany("GraUzytkownikaCollection")
                        .HasForeignKey("GraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraUzytkownika_Gra");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("GraUzytkownikaCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraUzytkownika_Uzytkownik");

                    b.Navigation("Gra");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownikaNaPlatformie", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Platformy.Models.Platforma", "Platforma")
                        .WithMany("GraUzytkownikaNaPlatformieCollection")
                        .HasForeignKey("PlatformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraUzytkownikaNaPlatformie_Platforma");

                    b.HasOne("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownika", "Gra")
                        .WithMany("GraUzytkownikaNaPlatformieCollection")
                        .HasForeignKey("UzytkownikId", "GraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraUzytkownikaNaPlatformie_GraUzytkownika");

                    b.Navigation("Gra");

                    b.Navigation("Platforma");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Platformy.Models.UzytkownikPlatforma", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Platformy.Models.Platforma", "Platforma")
                        .WithMany("UzytkownikPlatformaCollection")
                        .HasForeignKey("PlatformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UzytkownikPlatforma_Platforma");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("UzytkownikPlatformaCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UzytkownikPlatforma_Uzytkownik");

                    b.Navigation("Platforma");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Powiadomienia.Models.Powiadomienie", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Powiadomienia.Models.TypPowiadomienia", "TypPowiadomienia")
                        .WithMany("PowiadomienieCollection")
                        .HasForeignKey("TypPowiadomieniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Powiadomienie_TypPowiadomienia");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("PowiadomienieCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Powiadomienie_Uzytkownik");

                    b.Navigation("TypPowiadomienia");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.JezykProfilu", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Profile.Models.Jezyk", "Jezyk")
                        .WithMany("JezykProfiluCollection")
                        .HasForeignKey("JezykId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykProfilu_Jezyk");

                    b.HasOne("Squadra.Server.Modules.Profile.Models.StopienBieglosciJezyka", "StopienBieglosciJezyka")
                        .WithMany("JezykUzytkownikaCollection")
                        .HasForeignKey("StopienBieglosciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykUzytkownika_StopienBieglosci");

                    b.HasOne("Squadra.Server.Modules.Profile.Models.Profil", "Profil")
                        .WithMany("JezykUzytkownikaCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("JezykProfilu_Profil");

                    b.Navigation("Jezyk");

                    b.Navigation("Profil");

                    b.Navigation("StopienBieglosciJezyka");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Profil", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik")
                        .WithOne("Profil")
                        .HasForeignKey("Squadra.Server.Modules.Profile.Models.Profil", "IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Squadra.Server.Modules.Profile.Models.Region", "Region")
                        .WithMany("ProfilCollection")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Profil_Region");

                    b.HasOne("Squadra.Server.Modules.Profile.Models.Status", "Status")
                        .WithMany("ProfilCollection")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Profil_Status");

                    b.Navigation("Region");

                    b.Navigation("Status");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Region", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Profile.Models.Kraj", "Kraj")
                        .WithMany("RegionCollection")
                        .HasForeignKey("KrajId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Region_Kraj");

                    b.Navigation("Kraj");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Kategoria", b =>
                {
                    b.HasOne("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", "Gra")
                        .WithMany("KategoriaCollection")
                        .HasForeignKey("IdGry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gra");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Rola", b =>
                {
                    b.HasOne("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", "Gra")
                        .WithMany("RolaCollection")
                        .HasForeignKey("IdGry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gra");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Statystyka", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Statystyki.Models.Kategoria", "Kategoria")
                        .WithMany("StatystykaCollection")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Statystyka_Kategoria");

                    b.HasOne("Squadra.Server.Modules.Statystyki.Models.Rola", "Rola")
                        .WithMany("StatystykaCollection")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Statystyka_Rola");

                    b.Navigation("Kategoria");

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.StatystykaUzytkownika", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Statystyki.Models.Statystyka", "Statystyka")
                        .WithMany("StatystykaUzytkownikaCollection")
                        .HasForeignKey("StatystykaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("StatystykaUzytkownika_Statystyka");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("StatystykaUzytkownikaCollection")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("StatystykaUzytkownika_Uzytkownik");

                    b.Navigation("Statystyka");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Wiadomosci.Models.Wiadomosc", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Nadawca")
                        .WithMany("WiadomosciNadaneCollection")
                        .HasForeignKey("IdNadawcy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Wiadomosc_Nadawca");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Odbiorca")
                        .WithMany("WiadomosciOdebraneCollection")
                        .HasForeignKey("IdOdbiorcy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Wiadomosc_Odbiorca");

                    b.HasOne("Squadra.Server.Modules.Wiadomosci.Models.TypWiadomosci", "TypWiadomosci")
                        .WithMany("WiadomosciCollection")
                        .HasForeignKey("IdTypuWiadomosci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Wiadomosc_Typ_Wiadomosci");

                    b.Navigation("Nadawca");

                    b.Navigation("Odbiorca");

                    b.Navigation("TypWiadomosci");
                });

            modelBuilder.Entity("Squadra.Server.Modules.WspieraneGry.Models.GraNaPlatformie", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Platformy.Models.Platforma", "Platforma")
                        .WithMany("GraNaPlatformieCollection")
                        .HasForeignKey("IdPlatformy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraNaPlatformie_Platforma");

                    b.HasOne("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", "WspieranaGra")
                        .WithMany("GraNaPlatformieCollection")
                        .HasForeignKey("IdWspieranejGry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("GraNaPlatformie_WspieranaGra");

                    b.Navigation("Platforma");

                    b.Navigation("WspieranaGra");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Znajomosci.Models.Znajomi", b =>
                {
                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik1")
                        .WithMany("ZnajomiJakoPierwszyCollection")
                        .HasForeignKey("IdUzytkownika1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Znajomi_Uzytkownik1");

                    b.HasOne("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", "Uzytkownik2")
                        .WithMany("ZnajomiJakoDrugiCollection")
                        .HasForeignKey("IdUzytkownika2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Znajomi_Uzytkownik2");

                    b.Navigation("Uzytkownik1");

                    b.Navigation("Uzytkownik2");
                });

            modelBuilder.Entity("Squadra.Server.Modules.BibliotekaGier.Models.GraUzytkownika", b =>
                {
                    b.Navigation("GraUzytkownikaNaPlatformieCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Platformy.Models.Platforma", b =>
                {
                    b.Navigation("GraNaPlatformieCollection");

                    b.Navigation("GraUzytkownikaNaPlatformieCollection");

                    b.Navigation("UzytkownikPlatformaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Powiadomienia.Models.TypPowiadomienia", b =>
                {
                    b.Navigation("PowiadomienieCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Jezyk", b =>
                {
                    b.Navigation("JezykProfiluCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Kraj", b =>
                {
                    b.Navigation("RegionCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Profil", b =>
                {
                    b.Navigation("JezykUzytkownikaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Region", b =>
                {
                    b.Navigation("ProfilCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.Status", b =>
                {
                    b.Navigation("ProfilCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Profile.Models.StopienBieglosciJezyka", b =>
                {
                    b.Navigation("JezykUzytkownikaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Kategoria", b =>
                {
                    b.Navigation("StatystykaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Rola", b =>
                {
                    b.Navigation("StatystykaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Statystyki.Models.Statystyka", b =>
                {
                    b.Navigation("StatystykaUzytkownikaCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Uzytkownicy.Models.Uzytkownik", b =>
                {
                    b.Navigation("GraUzytkownikaCollection");

                    b.Navigation("PowiadomienieCollection");

                    b.Navigation("Profil");

                    b.Navigation("StatystykaUzytkownikaCollection");

                    b.Navigation("UzytkownikPlatformaCollection");

                    b.Navigation("WiadomosciNadaneCollection");

                    b.Navigation("WiadomosciOdebraneCollection");

                    b.Navigation("ZnajomiJakoDrugiCollection");

                    b.Navigation("ZnajomiJakoPierwszyCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.Wiadomosci.Models.TypWiadomosci", b =>
                {
                    b.Navigation("WiadomosciCollection");
                });

            modelBuilder.Entity("Squadra.Server.Modules.WspieraneGry.Models.WspieranaGra", b =>
                {
                    b.Navigation("GraNaPlatformieCollection");

                    b.Navigation("GraUzytkownikaCollection");

                    b.Navigation("KategoriaCollection");

                    b.Navigation("RolaCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
